version: '3.8'

networks:
  monitor:
    driver: bridge
  replica:
    driver: bridge

services:
  mysql:
    image: mysql:8
    container_name: mysql_container
    environment:
      - MYSQL_ROOT_PASSWORD=yujinlee
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    container_name: redis
    image: redis:6.2
    ports:
      - "6379:6379"
    networks:
      - monitor
      - replica
    command: redis-server --bind 0.0.0.0 --protected-mode no
    restart: always

  replica:
    container_name: replica
    image: redis:6.2
    ports:
      - "6378:6379"
    networks:
      - replica
    volumes:
      - ./redis/conf:/usr/local/etc/redis/
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always

  replica2:
    container_name: replica2
    image: redis:6.2
    ports:
      - "6377:6379"
    networks:
      - replica
    volumes:
      - ./redis/conf:/usr/local/etc/redis/
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: root
    volumes:
      - ./prometheus/config:/etc/prometheus
      - ./prometheus/data:/prometheus
    ports:
      - 9090:9090
    networks:
      - monitor
    restart: always

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=yujinlee
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    networks:
      - monitor
    restart: always

  redis-exporter:
    container_name: redis-exporter
    image: oliver006/redis_exporter:latest
    environment:
      - REDIS_ADDR=redis://redis:6379
    ports:
      - 9121:9121
    depends_on:
      - prometheus
    networks:
      - monitor
    restart: always

volumes:
  mysql_data: