spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/fastsns"
    username: root
    password: yujinlee
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  data:
      redis:
        host: 127.0.0.1
        port: 6379
  session:
    store-type: redis


server:
  port: 8080
  address: 0.0.0.0
